services:
  postgres:
    container_name: account-manager-postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=account-manager
      - POSTGRES_PASSWORD=27fa016fc5a25e8177a60ccd
      - POSTGRES_DB=account-manager
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

networks:
  default: {}
